### ISSUE TITLE
TypeError: int() argument must be a string, a bytes-like object or a number, not 'Tensor'

### ISSUE THREAD

**Issue by onlyonewater** [IsaacChanghau/VSLNet#1]
Thank you  very much for making the code open source.But I have a problem, when I use 
`query_features = tf.transpose(query_features, perm=[0, 2, 1]) 
query_features = conv1d(query_features, dim=1, use_bias=True, reuse=reuse, name='dense')`. There is an error as follows: TypeError: int() argument must be a string, a bytes-like object or a number, not 'Tensor'. I am very confused.

**Comment by IsaacChanghau** [comment]
@onlyonewater are you using the same packages list in the instructions? I tested just now, it works. No such error reported. Could you provide more details of the error info?

**Comment by onlyonewater** [comment]
Thank you very much for your reply, I have solved this error. But I am confused that when I run the command `python run_tacos.py --mode test`, I got a higher result than in the paper. The results are as follows: 
Rank@1, IoU=0.3:	45.69
Rank@1, IoU=0.5:	32.67
Rank@1, IoU=0.7:	19.27
mean IoU       :	32.30,
So, What's wrong?

**Comment by IsaacChanghau** [comment]
Solved.
