### ISSUE TITLE
max length of tacos ,charades-sta and ActivityNet Cap

### ISSUE THREAD

**Issue by TAY-985** [IsaacChanghau/VSLNet#13]
hello，
in a bach ,How do you load video features of different lengths into a tensor? padding them to a max length? if so, what is the max length for tacos ,charades-sta and ActivityNet Cap , respectively?

**Comment by 26hzhang** [comment]
@TAY-985 Yes, padding them to a pre-set max length, you may refer the function ``pad_video_seq'' in ``util/data_util.py''. The max_length is set as 128 for these datasets. And the hyper-param is controlled by ``--max_pos_len'' in ``main.py''.
