### ISSUE TITLE
Reproduce on TACoS

### ISSUE THREAD

**Issue by minjoong507** [IsaacChanghau/VSLNet#21]
Hi there. Thanks for sharing your great work!

I'm trying to reproduce the results in Table 2. (on TACoS dataset)

However, my results and the report in Table 2 are totally different.

Can you give me a detail to reproduce the results in Table 2?

![image](https://user-images.githubusercontent.com/49550490/204193191-3070ace1-5f64-47d6-85dc-136c37e363ab.png)

**Comment by EricLina** [comment]
hello, have you solved the problem?
Did you use the pytorch implementation?

**Comment by EricLina** [comment]
Rank@1, IoU=0.3:        39.39
Rank@1, IoU=0.5:        28.12
Rank@1, IoU=0.7:        15.90
mean IoU       :        28.23

**Comment by minjoong507** [comment]
Hi @EricLina,

If you ask for differences in the model's performances, the possible reason for this might be using different visual features.

Quoting from [2], "Note 2D-TAN [1] pre-processes the TACoS dataset, making it slightly different from the original one."

As shown in [2], there is a clear difference in performance when using the pre-processed visual features from [1].

I achieved higher performance on TACoS than what was reported in the original paper because this repository utilized the visual features from [1].

[1] Learning 2D Temporal Adjacent Networks for Moment Localization with Natural Language, AAAI 2020

[2] Parallel Attention Network with Sequence Matching for Video Grounding, ACL 2021
