### ISSUE TITLE
About parameters

### ISSUE THREAD

**Issue by Huntersxsx** [IsaacChanghau/VSLNet#6]

**Comment by Huntersxsx** [comment]
Hello, thank you for your great work. I want to know the total parameters of your model,  I tried the pytorch code, but the get_data_loader function in data_utils.py needs to load a ".pkl" file, I don't know where is the file or can you provide the parameters of your model?

**Comment by IsaacChanghau** [comment]
I have rewrote the codes and upload all the features after expanding the capacity of my Box drive. I think you may try it again?
