### ISSUE TITLE
sh: -c: line 0: syntax error near unexpected token `('

### ISSUE THREAD

**Issue by timemanager-001** [IsaacChanghau/VSLNet#7]
when i try extract_activitynet.py，I got the following error: sh: -c: line 0: syntax error near unexpected token `('

How to deal with it?

**Comment by IsaacChanghau** [comment]
I am not sure how it happens actually, maybe due to the package version? Actually, I have rewrote the codes and uploaded all the features after expanding the capacity of my Box drive. You can try it again?
