### ISSUE TITLE
activitynet video  

### ISSUE THREAD

**Issue by jun0wanan** [IsaacChanghau/VSLNet#9]
hi,

do you mind share video source  ?

Best,
wishes

**Comment by onlyonewater** [comment]
you can download the org videos like https://github.com/activitynet/ActivityNet/tree/master/Crawler or https://github.com/activitynet/ActivityNet/tree/master/Crawler, it may help you.

**Comment by 26hzhang** [comment]
@jun0wanan The video source of ActivityNet is around 220GB, which is too huge to share directly. I have provided the scripts and codes to download the video from YouTube directly, per "prepare/download_activitynet_video.py". And you can also refer the solution provided by @onlyonewater to download the videos.

@onlyonewater Thanks for solving this issue.
